import { CURRENCY_SYMBOL } from './constants';

/**
 * Format a number as Ghana Cedi currency.
 */
export function formatCurrency(amount: number): string {
    return `${CURRENCY_SYMBOL}${amount.toLocaleString('en-GH', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    })}`;
}

/**
 * Compute time remaining from now until a future date.
 */
export function getTimeRemaining(endTime: string | Date): {
    total: number;
    days: number;
    hours: number;
    minutes: number;
    seconds: number;
    isExpired: boolean;
} {
    const end = new Date(endTime).getTime();
    const now = Date.now();
    const total = Math.max(0, end - now);

    return {
        total,
        days: Math.floor(total / (1000 * 60 * 60 * 24)),
        hours: Math.floor((total / (1000 * 60 * 60)) % 24),
        minutes: Math.floor((total / (1000 * 60)) % 60),
        seconds: Math.floor((total / 1000) % 60),
        isExpired: total <= 0,
    };
}

/**
 * Human-readable relative time (e.g., "2 hours ago").
 */
export function timeAgo(date: string | Date): string {
    const seconds = Math.floor((Date.now() - new Date(date).getTime()) / 1000);

    const intervals: [number, string][] = [
        [31536000, 'year'],
        [2592000, 'month'],
        [86400, 'day'],
        [3600, 'hour'],
        [60, 'minute'],
        [1, 'second'],
    ];

    for (const [secondsInUnit, unit] of intervals) {
        const count = Math.floor(seconds / secondsInUnit);
        if (count >= 1) {
            return `${count} ${unit}${count > 1 ? 's' : ''} ago`;
        }
    }

    return 'just now';
}

/**
 * Generate initials from a name (for avatar fallback).
 */
export function getInitials(name: string): string {
    const parts = name.split(/[\s_.-]+/).filter(Boolean);
    if (parts.length === 1) return parts[0].substring(0, 2).toUpperCase();
    return parts
        .map((n) => n[0])
        .join('')
        .toUpperCase()
        .slice(0, 2);
}

/**
 * Merge Tailwind class names, filtering out falsy values.
 */
export function cn(...classes: (string | undefined | null | false)[]): string {
    return classes.filter(Boolean).join(' ');
}

/**
 * Format a user's name for privacy by returning their initials (e.g., "John Doe" -> "JD", "tiekujason_4dbab4" -> "TJ", "tiekuJason" -> "TJ")
 */
export function formatDisplayName(name?: string | null): string {
    if (!name) return 'AN'; // Anonymous

    // Remove email domain if it's an email
    let cleanName = name.includes('@') ? name.split('@')[0] : name;

    // Split by common separators (spaces, underscores, dots, hyphens)
    const rawParts = cleanName.split(/[\s_.-]+/);
    const parts = rawParts.filter(Boolean); // remove empty parts

    if (parts.length === 0) return 'AN';

    // Discard trailing random hex string commonly generated by Supabase
    let validParts = parts;
    if (parts.length > 1) {
        const lastPart = parts[parts.length - 1];
        if ((/^[0-9a-fA-F]{4,}$/.test(lastPart)) || (/^[0-9]+$/.test(lastPart))) {
            validParts = parts.slice(0, -1);
        }
    }

    if (validParts.length === 0) return 'AN';

    // If we have multiple parts, take the first letter of the first two parts
    if (validParts.length >= 2) {
        return (validParts[0].charAt(0) + validParts[1].charAt(0)).toUpperCase();
    }

    // If we only have one part (e.g. "tiekujason" or "tiekuJason")
    const singleName = validParts[0];

    // Check for camelCase (e.g "tiekuJason")
    const uppercaseMatches = singleName.match(/[A-Z]/g);
    if (uppercaseMatches && uppercaseMatches.length > 0) {
        // First letter + first uppercase letter found
        return (singleName.charAt(0) + uppercaseMatches[0]).toUpperCase();
    }

    // Default: grab the first two letters of the string
    return singleName.substring(0, 2).toUpperCase();
}
